FROM grafana/grafana:6.1.6


USER root
RUN chown -R root:root /etc/grafana && \
chmod -R a+r /etc/grafana && \
chown -R grafana:grafana /var/lib/grafana && \
chown -R grafana:grafana /usr/share/grafana

EXPOSE 3000
