FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.0

#COPY ./elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
#COPY ./jvm.options /usr/share/elasticsearch/config/jvm.options

EXPOSE 9200 9300
